### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#489]
- [x] 0:10 Check Covasim, HPVsim, and FPsim tests
- [x] 0:30 Check test coverage
- [x] 1:00 Review diffs/update changelog
- [x] 1:00 Re-read tutorials and add summaries
- [x] 0:30 Push new version
- [x] 0:10 Update paper
- [x] 0:20 Notify people (CSR, docs)

Check `isjupyter()` for:
- [x] IPython [Linux/Mac]
- [x] Jupyter Notebook [Linux/Mac/Windows]
- [x] JupyterLab [Linux]
- [x] Spyder [Linux]
- [x] VS Code notebook [Linux/Mac/Windows]
- [x] PyCharm [Linux]
- [x] Dataspell [Mac]
- [x] Binder
- [x] Google Colab

**Comment by cliffckerr** [comment]
Done
